---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spaceborscht-control
  namespace: spaceborscht
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - spaceborscht
  selector:
    matchLabels:
      app: control
  podMetricsEndpoints:
    - targetPort: 3000
      path: /metrics
  
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spaceborscht-engine
  namespace: spaceborscht
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - spaceborscht 
  selector:
    matchLabels:
      app: engine
  podMetricsEndpoints:
    - targetPort: 3001 
      path: /metrics
  
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spaceborscht-telemetry
  namespace: spaceborscht
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - spaceborscht 
  selector:
    matchLabels:
      app: telemetry
  podMetricsEndpoints:
    - targetPort: 3002 
      path: /metrics
  
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spaceborscht-comms
  namespace: spaceborscht
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - spaceborscht 
  selector:
    matchLabels:
      app: comms
  podMetricsEndpoints:
    - targetPort: 3003 
      path: /metrics
  
