prometheus:
  prometheusSpec:
    podMonitorSelector: 
      matchLabels:
        release: kube-prometheus-stack
    podMonitorNamespaceSelector: 
      matchNames:
        - spaceborscht
    ruleSelector: 
      matchLabels:
        release: kube-prometheus-stack
    ruleNamespaceSelector: {}
