apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podinfo
  namespace: podinfo
  labels:
    release: kube-prometheus-stack  # Этот лейбл должен совпадать с podMonitorSelector
spec:
  namespaceSelector:
    matchNames:
      - podinfo                     # Неймспейс, в котором ищем поды
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo  # Лейблы подов, которые нужно мониторить
  podMetricsEndpoints:
    - port: http                    # Имя порта (из spec.containers[].ports в деплойменте)
      path: /metrics